apiVersion: v1
kind: Service
metadata:
  name: kubernates-basic-web-service
spec:
  type: NodePort
  selector: 
    app: kubernates-basic-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080 